import Link from "next/link";
import type { Metadata } from "next";
import BookingOverview from "../components/BookingOverview";
import HoursCard from "../components/HoursCard";
import MapEmbed from "../components/MapEmbed";
import ServiceCard from "../components/ServiceCard";
import SiteFooter from "../components/SiteFooter";
import SiteHeader from "../components/SiteHeader";
import { bookingHref, bookingLabel, pageCopy, salonConfig, site } from "../site-data";
import { pageMetadata } from "../seo";

export const metadata: Metadata = pageMetadata("booking");

export default function BookingPage() {
  return <main className="inner-page booking-page"><SiteHeader inner /><section className="inner-hero"><div className="inner-hero-copy"><p className="eyebrow">{pageCopy.pages.booking.eyebrow}</p><h1>Wunsch. Termin. <em className="heading-accent">Vorfreude.</em></h1><p>{pageCopy.pages.booking.intro}</p><div className="hero-actions"><a className="button button-primary" href={bookingHref}>{bookingLabel}</a><Link className="text-link" href="/oeffnungszeiten/">Kontakt ansehen <span aria-hidden="true">→</span></Link></div></div><div className="inner-hero-mark" aria-hidden="true"><span>{salonConfig.logo.mark}</span></div></section><section className="booking-page-intro"><p className="section-kicker">So funktioniert es</p><h2>Persönlich. <em className="heading-accent">Direkt.</em> Unkompliziert.</h2><p>{salonConfig.content.booking.overviewIntro}</p><BookingOverview /></section><section className="services-section booking-services" aria-labelledby="booking-services-title"><div className="section-heading section-heading-light"><p className="section-kicker">Leistungsbereiche</p><h2 id="booking-services-title">Alles für <em className="heading-accent">Ihren Look.</em></h2><p>{pageCopy.home.serviceIntro}</p></div><div className="service-list">{salonConfig.services.filter((service) => service.enabled).map((service) => <ServiceCard key={service.slug} {...service} href={bookingHref} />)}</div></section><section className="booking-details-grid" aria-label="Termin- und Saloninformationen"><HoursCard /><article className="booking-details-card"><p className="section-kicker">Adresse &amp; Kontakt</p><h2>Direkt und <em className="heading-accent">übersichtlich.</em></h2><p className="inner-address">{site.name}<br />{site.owner ? <>{site.owner}<br /></> : null}{site.address[0]}<br />{site.address[1]}</p>{site.phoneHref ? <a className="button button-primary" href={site.phoneHref}>{site.phoneDisplay} anrufen</a> : <p>Der bestätigte Kontaktweg wird im Kundenprofil sichtbar verknüpft.</p>}</article></section><section className="booking-map-section"><div><p className="section-kicker">Anfahrt</p><h2>Ihr Weg zum <em className="heading-accent">Salon.</em></h2><p>{salonConfig.map.consentCopy}</p></div><MapEmbed directionsUrl={salonConfig.links.directionsUrl} embedUrl={salonConfig.links.mapEmbedUrl} title={salonConfig.map.title} /></section><section className="inner-note-section"><p className="section-kicker">Termin-Anfrage</p><h2>Direkt mit dem <em className="heading-accent">Salon.</em></h2><p>{salonConfig.content.booking.note}</p><a className="button button-primary" href={bookingHref}>{salonConfig.content.booking.primaryCtaLabel}</a></section><SiteFooter /><a className="mobile-call-bar" href={bookingHref}><span aria-hidden="true">↗</span>{bookingLabel}</a></main>;
}
